version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - API_KEY=your-api-key
      - PTERO_BASE_URL=https://your-pterodactyl-panel.com/api
    volumes:
      - ./backend:/usr/src/app